language: csharp
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test SeatsioDotNet.Test

deploy:
  provider: script
  script: sh deploy.sh $NUGET_API_KEY
  on:
    tags: true