name: 'Push new release to Nuget'

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - run: dotnet pack --configuration Release SeatsioDotNet/SeatsioDotNet.csproj -o SeatsioDotNet
      - run: dotnet nuget push SeatsioDotNet/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}