name: 'Release'

on:
  workflow_dispatch:
  release:
    types: [created]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - run: dotnet pack SeatsioDotNet/SeatsioDotNet.csproj
      - run: dotnet nuget push --source SeatsioDotNet --api-key ${{secrets.NUGET_API_KEY}}