on:
  release:
    types: [created]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.0.0
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: SeatsioDotNet/SeatsioDotNet.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}